### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by farzanenaghshbandy** [ellio167/AEM-4501-matlab-codes#1]
hi my friend
thank you very mach 

function [M, K] = assemble_PD_truss_fem(PD)

%        EqnNumbering = Node to global DOF numbering as @(Node, NodeDOF)()
%
function PlotTruss(PD, scl, plotlab, plotdef)
function [m, k, T] = truss_local_matrices(Pos1, Pos2, Material)

I used your code and my problem is that EqnNumbering input is not given in this function and code need this for result , and if i have not EqnNumbering other function will not run .
please help me for my problem and i need tomarrow this.

**Comment by ellio167** [comment]
Use `PD_truss_static.m` instead of `assemble_PD_truss_fem`
